version: 1.0

cache: true

registration:
  socialLogins:
    - "discord"
    - "facebook"
    - "github"
    - "google"
    - "openid"

endpoints:
  openAI:
    apiKey: "${OPENAI_API_KEY}"
    baseURL: "https://api.openai.com/v1"
    models:
      default:
        - gpt-4o-mini
      fetch: false
    titleModel: gpt-4o-mini
    summarize: false
    summaryModel: gpt-4o-mini
    modelDisplayLabel: "ChatGPT-4o Mini"

